version: '3.8'

services:

  web:
    build: .
    volumes:
      - .:/base
    ports:
      - 3000:3000

    # stdin_open: true    # debug
    # tty: true           # debug
    # command: bash
    
    command: rails s -b 0.0.0.0
    # command: bash -c 'rm -f /base/tmp/pids/server.pid && rails s -b 0.0.0.0'

